MESSAGE /test/urlencoded/query/encoder {
GET REQUEST {
INT64 t1 = t;
INT32 t2 = tt;
DOUBLE t3 = ttt;
STRING t4 = tttt;
}
GET RESPONSE {
STRING x1 = x;
}
}

MESSAGE /test/urlencoded/form/encoder {
POST REQUEST {
INT64 t1 = t;
INT32 t2 = tt;
DOUBLE t3 = ttt;
STRING t4 = tttt;
}
POST RESPONSE {
STRING x1 = x;
}
}

MESSAGE /test/multipart/encoder {
POST REQUEST {
INT64 number = number;
BOOL bool = bool;
STRING string = string;
BLOB data = data;
FILE file = file;
}
POST RESPONSE {
STRING x1 = x;
}
}

MESSAGE /test/json/encoder {
POST REQUEST {
INT64 t1 = t;
INT32 t2 = tt;
DOUBLE t3 = ttt;
STRING t4 = tttt;
ARRAY<STRING> t5 = ttttt;
}
POST RESPONSE {
STRING x1 = x;
}
}

MESSAGE /sticker/$mediaId {
GET REQUEST {
    STRING defaultMap;
}

GET RESPONSE {
INT32 code = code;
ARRAY<OnlineStickerTemplate> templates = data;
    STRING defaultMap;
}
}

STRUCT OnlineStickerTemplate {
STRING url = url;
DOUBLE x = x;
DOUBLE y = y;
DOUBLE width = w;
DOUBLE height = h;
DOUBLE angle = angle;
    STRING defaultMap;
}

MESSAGE /under_line {
GET REQUEST {
    TestNestedStruct a;
}
GET RESPONSE {
    ARRAY<TestNestedStruct> b;
}
}

MESSAGE /test/nested/message {
GET REQUEST {
ARRAY<STRING> a1 = ae;
DICT<STRING, STRING> d1 = de;
ARRAY<ARRAY<ARRAY<STRING>>> aaa1 = aaae;
ARRAY<DICT<STRING, STRING>> ad1 = ade;
DICT<STRING, DICT<STRING, STRING>> dd1 = dde;
DICT<STRING, ARRAY<STRING>> da1 = dae;
DICT<STRING, ARRAY<DICT<STRING, ARRAY<STRING>>>> dada1 = dadae;
ARRAY<DICT<STRING, ARRAY<DICT<STRING, STRING>>>> adad1 = adade;
}
GET RESPONSE {
ARRAY<STRING> a1 = ae;
DICT<STRING, STRING> d1 = de;
ARRAY<ARRAY<STRING>> aa1 = aae;
ARRAY<DICT<STRING, STRING>> ad1 = ade;
DICT<STRING, DICT<STRING, STRING>> dd1 = dde;
DICT<STRING, ARRAY<STRING>> da1 = dae;
}
}

STRUCT TestNestedStruct {
ARRAY<STRING> a;
DICT<STRING, STRING> d;
ARRAY<ARRAY<STRING>> aa;
ARRAY<DICT<STRING, STRING>> ad;
DICT<STRING, DICT<STRING, STRING>> dd;
DICT<STRING, ARRAY<STRING>> da;
DICT<STRING, ARRAY<DICT<STRING, ARRAY<STRING>>>> dada;
}

MESSAGE /get {
GET REQUEST {
INT64 int64;
INT32 int32;
BOOL bool;
DOUBLE double;
STRING string;
ARRAY<STRING> array;
}

GET RESPONSE {
HTTPBinGetArgs args;
}
}

STRUCT HTTPBinGetArgs {
INT64 int64;
INT32 int32;
BOOL bool;
DOUBLE double;
STRING string;
ARRAY<STRING> array;
}

MESSAGE /post {

POST REQUEST {
FILE data;
}

POST RESPONSE {
}
}

MESSAGE /ungined/test {
GET REQUEST {
UINT32 uint32;
UINT64 uint64;
}

GET RESPONSE {
UINT32 uint32;
UINT64 uint64;
}
}

MESSAGE(Testing1) /cgi-a/wx {
    GET REQUEST {}
    GET RESPONSE {}
}

MESSAGE(Testing2) /test/%^&**(/\//$xxxx {
    GET REQUEST {
        INT64 a;
        INT32 b = STRING;
    }

    GET RESPONSE {
        BOOL c = \;;
        STRING d = ^&**;
        FILE e = a123&*;
    }
}

MESSAGE(Testing3) /test/?/message&_name/哎呦 {
    GET REQUEST {
        STRING x = x;
        STRING name = 呵呵哒;
    }
    GET RESPONSE {}
}

