MESSAGE /test/urlencoded/query/encoder {
GET REQUEST {
INT64 t1 = t;
INT32 t2 = tt;
DOUBLE t3 = ttt;
STRING t4 = tttt;
}
GET RESPONSE {
STRING x1 = x;
}
}

MESSAGE /test/urlencoded/form/encoder {
POST REQUEST {
INT64 t1 = t;
INT32 t2 = tt;
DOUBLE t3 = ttt;
STRING t4 = tttt;
}
POST RESPONSE {
STRING x1 = x;
}
}

MESSAGE /test/multipart/encoder {
POST REQUEST {
INT64 number = number;
BOOL bool = bool;
STRING string = string;
BLOB data = data;
FILE file = file;
}
POST RESPONSE {
STRING x1 = x;
}
}

MESSAGE /test/json/encoder {
POST REQUEST {
INT64 t1 = t;
INT32 t2 = tt;
DOUBLE t3 = ttt;
STRING t4 = tttt;
ARRAY<STRING> t5 = ttttt;
}
POST RESPONSE {
STRING x1 = x;
}
}

MESSAGE /sticker/$mediaId {
GET REQUEST {
    STRING defaultMap;
}

GET RESPONSE {
INT32 code = code;
ARRAY<OnlineStickerTemplate> templates = data;
    STRING defaultMap;
}
}

STRUCT OnlineStickerTemplate {
STRING url = url;
DOUBLE x = x;
DOUBLE y = y;
DOUBLE width = w;
DOUBLE height = h;
DOUBLE angle = angle;
    STRING defaultMap;
}



