# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'HTTPIDLDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for HTTPIDLDemo
  pod 'HTTPIDL', :path => '~/git/HTTPIDL'
end


target 'HTTPIDLDemoTests' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    
    # Pods for HTTPIDLDemo
    pod 'HTTPIDL', :path => '~/git/HTTPIDL'
end
